### ISSUE TITLE
Unable to add new 'electronic form'

### ISSUE THREAD

**Issue by ChrisBathory** [measure-2-improve/support#41]
##### What is the issue? 
The Add Electronic form screen, despite having the score widget turned on, doesn't give me an option to specify a template - and stops me from progressing.

##### What would you expect to happen?
should be able to add new electronic forms for either of my templates.

##### What steps are needed to replicate the issue?

login to chris
take menu 'Client Project Home' and click option to Add Electronic Form

can't complete Template field
**contents of console below:** reloading the phe page doesnt seem tohave any effect
base.js:13550 TypeError: Cannot read property 'name' of null
    at app.js:2780
    at processQueue (base.js:15961)
    at base.js:15977
    at Scope.$eval (base.js:17229)
    at Scope.$digest (base.js:17045)
    at Scope.$apply (base.js:17337)
    at done (base.js:11572)
    at completeRequest (base.js:11778)
    at XMLHttpRequest.requestLoaded (base.js:11711)(anonymous function) @ base.js:13550
base.js:13550 Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://www.m2itest.co.uk/chris/js/base.js:54026:12
    at http://www.m2itest.co.uk/chris/js/base.js:54845:19
    at publicLinkFn (http://www.m2itest.co.uk/chris/js/base.js:8276:29)
    at lazyCompilation (http://www.m2itest.co.uk/chris/js/base.js:8615:25)
    at boundTranscludeFn (http://www.m2itest.co.uk/chris/js/base.js:8414:16)
    at controllersBoundTransclude (http://www.m2itest.co.uk/chris/js/base.js:9143:20)
    at http://www.m2itest.co.uk/chris/js/base.js:54833:9
    at invokeLinkFn (http://www.m2itest.co.uk/chris/js/base.js:9694:9)
    at nodeLinkFn (http://www.m2itest.co.uk/chris/js/base.js:9093:11)
    at http://www.m2itest.co.uk/chris/js/base.js:9433:13 <div class="ui-select-container ui-select-bootstrap dropdown ng-pristine ng-untouched ng-valid ng-scope" ng-class="{open: $select.open}" ng-model="scoringCtrl.template" ng-required="true" ng-disabled="scoringCtrl.disabled">(anonymous function) @ base.js:13550
base.js:13550 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (base.js:55419)
    at ngModelWatch (base.js:26943)
    at Scope.$digest (base.js:17064)
    at Scope.$apply (base.js:17337)
    at done (base.js:11572)
    at completeRequest (base.js:11778)
    at XMLHttpRequest.requestLoaded (base.js:11711)(anonymous function) @ base.js:13550
2base.js:13550 Error: [ui.select:transcluded] Expected 1 .ui-select-match but got '0'.
    at http://www.m2itest.co.uk/chris/js/base.js:54026:12
    at http://www.m2itest.co.uk/chris/js/base.js:54845:19
    at publicLinkFn (http://www.m2itest.co.uk/chris/js/base.js:8276:29)
    at lazyCompilation (http://www.m2itest.co.uk/chris/js/base.js:8615:25)
    at boundTranscludeFn (http://www.m2itest.co.uk/chris/js/base.js:8414:16)
    at controllersBoundTransclude (http://www.m2itest.co.uk/chris/js/base.js:9143:20)
    at http://www.m2itest.co.uk/chris/js/base.js:54833:9
    at invokeLinkFn (http://www.m2itest.co.uk/chris/js/base.js:9694:9)
    at nodeLinkFn (http://www.m2itest.co.uk/chris/js/base.js:9093:11)
    at http://www.m2itest.co.uk/chris/js/base.js:9433:13 <div class="ui-select-container ui-select-bootstrap dropdown" ng-class="{open: $select.open}" ng-model="ctrl.selected" on-select="ctrl.select()">(anonymous function) @ base.js:13550
2base.js:13550 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (base.js:55419)
    at ngModelWatch (base.js:26943)
    at Scope.$digest (base.js:17064)
    at Scope.$apply (base.js:17337)
    at done (base.js:11572)
    at completeRequest (base.js:11778)
    at XMLHttpRequest.requestLoaded (base.js:11711)

![image](https://cloud.githubusercontent.com/assets/19467251/15898242/593a4852-2d8f-11e6-8fca-4599ebea14e7.png)

##### What browser does the issue appear on?
Google Chrome

**Comment by Gillardo** [comment]
Uploaded latest version and this seems to now be fine

![image](https://cloud.githubusercontent.com/assets/7406381/16005292/66510d78-315e-11e6-9b71-55a1cb432586.png)

![image](https://cloud.githubusercontent.com/assets/7406381/16005311/830e0e70-315e-11e6-98dc-0d14f39261e6.png)
